cpu:
  svd: stm32f407.svd
  vector_table: 0x08008000
  #id: 0x1234_5678_BABE_1234_5678_BABE
regions:
  - name: NULL_forgiveness
    start: 0x00000000
    size: 4096
  - name: ROM
    start: 0x08000000
    load: fw_v3.5.4.bin
    size: 0x80000
  - name: RAM-CCM
    start: 0x10000000
    size: 0x18000
  - name: RAM
    start: 0x20000000
    size: 0x20000
framebuffers:
  - name: Touchscreen
    width: 480
    height: 320
    mode: rgb565
    sdl: true
  - name: LCD
    width: 3840
    height: 2400
    mode: gray8
    sdl: true
    downscale: 8
peripherals:
  software_spi:
    - name: SW_SPI_TOUCH
      cs: PD12
      clk: PD13
      mosi: PG4
      miso: PG3
devices:
  touchscreen:
    - peripheral: SW_SPI_TOUCH
      framebuffer: Touchscreen
      touch_detected_pin: PG6
      swap_x_y: true
      flip_x: true
      flip_y: true
  spi_flash:
    - peripheral: SPI2
      jedec_id: 0xef4016
      file: PMS_UI_001.bin
      size: 0x2000000
  usart_probe:
    - peripheral: USART1
  display:
    - peripheral: FSMC.BANK1
      framebuffer: Touchscreen
      cmd_addr_bit: 0x20000
  lcd:
    - peripheral: SPI1
      framebuffer: LCD
patches:
  # Generate these with ./asm.py
  # NOP systick delay
  - start: 0x0800b656
    data: [0x70, 0x47]
  - start: 0x0800b9c4
    data: [0x70, 0x47]
  # NOP usb init
  - start: 0x0801dd18
    data: [0x70, 0x47]
  # NOP delay_cycle
  - start: 0x0800d434
    data: [0x70, 0x47]
  # NOP delay_cycle
  - start: 0x0801b338
    data: [0x70, 0x47]
  # NOP display drawing
  # - start: 0x08018b58
  #  data: [0x70, 0x47]
  # NOP LCD init drawing
  - start: 0x0800e4da
    data: [0x70, 0x47]
  # NOP 200,000 of LCD init stuff
  - start: 0x080086e8
    data: [0x00, 0xbf]
  # RET usart3 something
  - start: 0x0800F738
    data: [0x70, 0x47]
  # RET adc1 something
  - start: 0x0800B928
    data: [0x70, 0x47]
  # Return -1 for a duration_now() that is triggered by tim3 intr. We don't have timers yet.
  - start: 0x0800b64c
    data: [0x4f, 0xf0, 0xff, 0x30, 0x70, 0x47]
